eDobromir/eDobromir/urls.py
from ckeditor_uploader import views as ckeditor_views
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.sitemaps.views import sitemap

from profile_account import urls as profile_accounts_urls
from comments import urls as comments_urls
from errors import urls as errors_urls
from eureka import urls as eureka_urls
from search import urls as search_urls
from votes import urls as vote_urls
from content import urls as content_urls
from concept import urls as concept_urls
from tags import urls as tags_urls
from linked import urls as linked_urls
from moderation import urls as moderation_urls
from notification import urls as notification_urls
from favorites import urls as favorites_urls
import sitemaps as sitemaps_urls
import rss as rss_urls


urlpatterns = [
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^panel/sterowania/swiatem/', include(admin.site.urls)),  # admin site

    url(r'^', include(search_urls, namespace='search')),
    url(r'^', include(eureka_urls, namespace='eureka')),
    url(r'^', include(errors_urls, namespace='errors')),
    url(r'^', include(vote_urls, namespace='votes')),
    url(r'^', include(comments_urls,  namespace='comments')),
    url(r'^', include(content_urls,  namespace='content')),
    url(r'^', include(concept_urls,  namespace='concept')),
    url(r'^', include(tags_urls,  namespace='tags')),
    url(r'^', include(linked_urls,  namespace='linked')),
    url(r'^', include(moderation_urls,  namespace='moderation')),
    url(r'^', include(notification_urls,  namespace='notification')),
    url(r'^', include(favorites_urls,  namespace='favorites')),
    url(r'^', include(profile_accounts_urls)),
    url(r'^', include(sitemaps_urls)),
    url(r'^', include(rss_urls)),

    url(r'^ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    url(r'^ckeditor/browse/', login_required(ckeditor_views.browse), name='ckeditor_browse'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

eDobromir/search/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import *

urlpatterns = [
    url(r'^$', SearchEurekaView.as_view(), name='search_eureka'),
    url(r'^waiting/$', SearchEurekaWaitingView.as_view(), name='search_eureka_waiting'),
    url(r'^concepts/$', SearchConceptView.as_view(), name='search_concept'),

    url(r'^search/eureka/$', SearchMixedEurekaView.as_view(), name='search_mixed_eureka'),
    url(r'^search/waiting/$', SearchMixedEurekaWaitingView.as_view(), name='search_mixed_eureka_waiting'),
    url(r'^search/concept/$', SearchMixedConceptView.as_view(), name='search_mixed_concept'),
    url(r'^search/everywhere/$', SearchMixedEverywhereView.as_view(), name='search_mixed_everywhere'),
]

eDobromir/tags/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *


urlpatterns = [
    url(r'^tag/list/$', TagListView.as_view(), name='tag_list'),
    url(r'^sympathizer/list/$', SympathizerListView.as_view(), name='sympathizer_list'),
    url(r'^sympathizer/create/$', SympathizerCreateView.as_view(), name='sympathizer_create'),
]

eDobromir/search/models.py
from __future__ import unicode_literals
from django.db import models

eDobromir/search/forms.py
# -*- coding: utf-8 -*-

from django import forms
from ckeditor.widgets import CKEditorWidget
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Field

class SearchForm(forms.Form):
    search_input = forms.CharField(max_length=100, label='Co cię interesuje? @użytkownik, #tag', required=False)

eDobromir/search/views.py
from .tables import SearchTable
from django_tables2 import RequestConfig
from django.views.generic import TemplateView
from eureka.models import Eureka
from concept.models import Concept
from django.utils.timezone import timedelta, now
from django.views.generic.list import ListView


class SearchEurekaView(ListView):
    model = Eureka
    template_name = 'search_eureka.html'

    def get_queryset(self):
        queryset = super(SearchEurekaView, self).get_queryset()
        queryset = queryset.filter(is_waiting=False, is_published=True)
        return queryset

    def get_context_data(self, **kwargs):
        table = SearchTable(self.get_queryset(), order_by='-published')
        RequestConfig(self.request, paginate={'per_page': 30}).configure(table)
        contex = super(SearchEurekaView, self).get_context_data(**kwargs)
        contex['active_page'] = 'search_eureka'
        contex['table'] = table
        return contex


class SearchEurekaWaitingView(ListView):
    model = Eureka
    template_name = 'search_eureka_waiting.html'

    def get_queryset(self):
        queryset = super(SearchEurekaWaitingView, self).get_queryset()
        queryset = queryset.filter(is_waiting=True, is_published=True)
        return queryset

    def get_context_data(self, **kwargs):
        table = SearchTable(self.get_queryset(), order_by='-popular')
        RequestConfig(self.request, paginate={'per_page': 30}).configure(table)
        contex = super(SearchEurekaWaitingView, self).get_context_data(**kwargs)
        contex['active_page'] = 'search_eureka_waiting'
        contex['table'] = table
        return contex


class SearchConceptView(ListView):
    model = Concept
    template_name = 'search_concept.html'

    def get_queryset(self):
        queryset = super(SearchConceptView, self).get_queryset()
        return queryset

    def get_context_data(self, **kwargs):
        table = SearchTable(self.get_queryset(), order_by='-active')
        RequestConfig(self.request, paginate={'per_page': 30}).configure(table)
        contex = super(SearchConceptView, self).get_context_data(**kwargs)
        contex['active_page'] = 'search_concept'
        contex['table'] = table
        return contex


class SearchMixedView(TemplateView):
    search_input = None
    split = None
    tags = None
    users = None
    text = None
    sympathizers = None

    when_convert = None

    def dispatch(self, request, *args, **kwargs):
        self.split = []
        self.tags = []
        self.users = []
        self.text = []
        self.sympathizers = []

        self.when = request.GET.get('when') or ''
        self.how = request.GET.get('sort') or ''
        if self.when:
            if self.when == 'day':
                self.when_convert = now() - timedelta(days=1)
            if self.when == 'week':
                self.when_convert = now() - timedelta(days=7)
            if self.when == 'month':
                self.when_convert = now() - timedelta(days=30)
            if self.when == 'year':
                self.when_convert = now() - timedelta(days=360)
            if self.when == 'eternity':
                self.when_convert = now() - timedelta(days=360 * 20)

        self.search_input = request.GET.get('search_input') or ''
        if self.search_input:
            self.split = self.search_input.split(' ')
            for split_item in self.split:
                if '#' in split_item:
                    tag = split_item.replace('#', '')
                    self.tags.append(tag)
                elif '@' in split_item:
                    user = split_item.replace('@', '')
                    self.users.append(user)
                elif '!' in split_item:
                    sympathizer = split_item.replace('!', '')
                    self.sympathizers.append(sympathizer)
                else:
                    self.text.append(split_item)
        return super(SearchMixedView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = kwargs
        context['active_page'] = 'search_mixed'
        context['search_input'] = self.search_input
        context['tags'] = self.tags
        context['sympathizers'] = self.sympathizers
        context['when'] = self.when
        context['how'] = self.how
        return context


class SearchMixedEurekaView(SearchMixedView):
    template_name = 'search_mixed_eureka.html'

    def get_queryset(self):
        queryset = Eureka.objects.filter(is_waiting=False, is_published=True)
        if self.when_convert:
            queryset = queryset.filter(published__gte=self.when_convert)
        if self.search_input:
            for user in self.users:
                queryset = queryset.filter(created_by__username=user)
            for tag in self.tags:
                queryset = queryset.filter(tags__name__in=[tag])
            for sympathizer in self.sympathizers:
                queryset = queryset.filter(sympathizers__name__in=[sympathizer])
            for word in self.text:
                queryset = queryset.filter(title__icontains=word)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(SearchMixedEurekaView, self).get_context_data(**kwargs)
        table = SearchTable(self.get_queryset(), order_by=self.how)
        RequestConfig(self.request, paginate={'per_page': 30}).configure(table)
        context['table'] = table
        context['where'] = 'eureka'
        return context


class SearchMixedEurekaWaitingView(SearchMixedView):
    template_name = 'search_mixed_eureka_waiting.html'

    def get_queryset(self):
        queryset = Eureka.objects.filter(is_waiting=True, is_published=True)
        if self.when_convert:
            queryset = queryset.filter(published__gte=self.when_convert)
        if self.search_input:
            for user in self.users:
                queryset = queryset.filter(created_by__username=user)
            for tag in self.tags:
                queryset = queryset.filter(tags__name__in=[tag])
            for sympathizer in self.sympathizers:
                queryset = queryset.filter(sympathizers__name__in=[sympathizer])
            for word in self.text:
                queryset = queryset.filter(title__icontains=word)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(SearchMixedEurekaWaitingView, self).get_context_data(**kwargs)
        table = SearchTable(self.get_queryset(), order_by=self.how)
        RequestConfig(self.request, paginate={'per_page': 30}).configure(table)
        context['table'] = table
        context['where'] = 'eureka_waiting'
        return context


class SearchMixedConceptView(SearchMixedView):
    template_name = 'search_mixed_concept.html'

    def get_queryset(self):
        queryset = Concept.objects.all()
        if self.when_convert:
            queryset = queryset.filter(published__gte=self.when_convert)
        if self.search_input:
            for user in self.users:
                queryset = queryset.filter(created_by__username=user)
            for tag in self.tags:
                queryset = queryset.filter(tags__name__in=[tag])
            for sympathizer in self.sympathizers:
                queryset = queryset.filter(sympathizers__name__in=[sympathizer])
            for word in self.text:
                queryset = queryset.filter(content__icontains=word)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(SearchMixedConceptView, self).get_context_data(**kwargs)
        table = SearchTable(self.get_queryset(), order_by=self.how)
        RequestConfig(self.request, paginate={'per_page': 30}).configure(table)
        context['table'] = table
        context['where'] = 'concept'
        return context


class SearchMixedEverywhereView(SearchMixedEurekaView, SearchMixedEurekaWaitingView, SearchMixedConceptView):
    template_name = 'search_mixed_everywhere.html'

    def get_context_data(self, **kwargs):
        context = super(SearchMixedEverywhereView, self).get_context_data(**kwargs)

        table_eureka = SearchTable(SearchMixedEurekaView.get_queryset(self), order_by=self.how)
        RequestConfig(self.request, paginate={'per_page': 10}).configure(table_eureka)

        table_eureka_waiting = SearchTable(SearchMixedEurekaWaitingView.get_queryset(self), order_by=self.how)
        RequestConfig(self.request, paginate={'per_page': 10}).configure(table_eureka_waiting)

        table_concept = SearchTable(SearchMixedConceptView.get_queryset(self), order_by=self.how)
        RequestConfig(self.request, paginate={'per_page': 10}).configure(table_concept)

        context['table_eureka'] = table_eureka
        context['table_eureka_waiting'] = table_eureka_waiting
        context['table_concept'] = table_concept
        context['where'] = 'everywhere'
        return context

eDobromir/search/templates/search_base.html
{% extends 'dashboard_sidebar_recent.html' %}
{% load static %}

{% block recent_content_sidebar_top %}
    <div class="col-xs-12">
        <a href="?sort=-published" class="link-tab {% if table.order_by|safe == '-published' %}link-tab-active{% endif %}">
            <i class="fa fa-hand-rock-o" aria-hidden="true"></i> Najnowsze
        </a>
        <a href="?sort=-active" class="link-tab {% if table.order_by|safe == '-active' %}link-tab-active{% endif %}">
            <i class="fa fa fa-hand-spock-o" aria-hidden="true"></i> Aktywne
        </a>
        <a href="?sort=-popular" class="link-tab {% if table.order_by|safe == '-popular' %}link-tab-active{% endif %}">
            <i class="fa fa fa-hand-scissors-o" aria-hidden="true"></i> Popularne
        </a>
    </div>
{% endblock %}

{% block content_sidebar_left %}
    {% block search_content_sidebar_left %}
    {% endblock %}
{% endblock %}

eDobromir/search/templates/search_concept.html
{% extends 'search_base.html' %}
{% load static %}
{% load tags_concept %}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load trans blocktrans from i18n %}
{% load bootstrap3 %}
{% load comments_templatetags %}
{% load eureka_templatetags %}

{% block search_content_sidebar_left %}
    <div class="col-xs-12 text-muted text_with_line">Koncepcje</div>
    {% for row in table.page.object_list|default:table.rows %}
        {% render_concept_preview_medium_extended row.record %}
        <div class="col-xs-12 text_with_line"></div>
    {% endfor %}
    {% render_comments_reply %}
    <div class="col-xs-12">
        {% bootstrap_pagination table.page url=request.get_full_path %}
    </div>
{% endblock %}

{% block content_sidebar_right_extended %}
    <div class="col-xs-12 text_with_line text-muted">
        Poczekalnia
        <span class="pull-right">
            <small>
                <a href="{% url 'search:search_eureka_waiting' %}" class="link-tab"><i class="fa fa-th-list" aria-hidden="true"></i></a>
            </small>
        </span>
    </div>
    {% render_eureka_waiting_random_list 3 %}

    <div class="col-xs-12 text_with_line text-muted">
        Główna
        <span class="pull-right">
            <small>
                <a href="{% url 'search:search_eureka' %}" class="link-tab"><i class="fa fa-th-list" aria-hidden="true"></i></a>
            </small>
        </span>
    </div>
    {% render_eureka_random_list 3 %}
{% endblock %}

eDobromir/search/templates/search_eureka.html
{% extends 'search_base.html' %}
{% load static %}
{% load tags_concept %}
{% load eureka_templatetags %}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load trans blocktrans from i18n %}
{% load bootstrap3 %}
{% load tags_templatetags %}

{% block title %}Twoje miejsce do dyskusji{% endblock %}

{% block search_content_sidebar_left %}
    <div class="col-xs-12 text-muted text_with_line">Główna</div>
    {% for row in table.page.object_list|default:table.rows %}
        {% render_eureka_preview_big row.record %}
        <div class="col-xs-12 text_with_line"></div>
    {% endfor %}
    <div class="col-xs-12">
        {% bootstrap_pagination table.page url=request.get_full_path %}
    </div>
{% endblock %}

{% block content_sidebar_right_extended %}
    <div class="col-xs-12 text_with_line text-muted">
        Koncepcje
        <span class="pull-right">
            <small>
                <a href="{% url 'search:search_concept' %}" class="link-tab"><i class="fa fa-th-list" aria-hidden="true"></i></a>
            </small>
        </span>
    </div>
    {% render_concept_preview_small_random_list 3 %}

    <div class="col-xs-12 text_with_line text-muted">
        Poczekalnia
        <span class="pull-right">
            <small>
                <a href="{% url 'search:search_eureka_waiting' %}" class="link-tab"><i class="fa fa-th-list" aria-hidden="true"></i></a>
            </small>
        </span>
    </div>
    {% render_eureka_waiting_random_list 3 %}
{% endblock %}

eDobromir/search/templates/search_eureka_waiting.html
{% extends 'search_base.html' %}
{% load static %}
{% load tags_concept %}
{% load eureka_templatetags %}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load trans blocktrans from i18n %}
{% load bootstrap3 %}

{% block title %}Poczekalnia{% endblock %}

{% block search_content_sidebar_left %}
    <div class="col-xs-12 text-muted text_with_line">Poczekalnia</div>
    {% for row in table.page.object_list|default:table.rows %}
        {% render_eureka_preview_big row.record %}
        <div class="col-xs-12 text_with_line"></div>
    {% endfor %}
    <div class="col-xs-12">
        {% bootstrap_pagination table.page url=request.get_full_path %}
    </div>
{% endblock %}

{% block content_sidebar_right_extended %}
    <div class="col-xs-12 text_with_line text-muted">
        Koncepcje
        <span class="pull-right">
            <small>
                <a href="{% url 'search:search_concept' %}" class="link-tab"><i class="fa fa-th-list" aria-hidden="true"></i></a>
            </small>
        </span>
    </div>
    {% render_concept_preview_small_random_list 2 %}

    <div class="col-xs-12 text_with_line text-muted">
        Główna
        <span class="pull-right">
            <small>
                <a href="{% url 'search:search_eureka' %}" class="link-tab"><i class="fa fa-th-list" aria-hidden="true"></i></a>
            </small>
        </span>
    </div>
    {% render_eureka_random_list 3 %}
{% endblock %}

eDobromir/search/templates/search_mixed.html
{% extends 'search_base.html' %}
{% load static %}
{% load tags_concept %}
{% load eureka_templatetags %}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load trans blocktrans from i18n %}
{% load bootstrap3 %}
{% load tags_concept %}
{% load tags_templatetags %}

{% block title %}Szukaj{% endblock %}

{% block recent_content_sidebar_top %}
    <div class="col-xs-12">
        <a href="?sort=-published&when={{ when }}&search_input={{ search_input|urlencode }}" class="link-tab {% if table.order_by|safe == '-published' %}link-tab-active{% endif %}">
            <i class="fa fa-hand-rock-o" aria-hidden="true"></i> Najnowsze
        </a>
        <a href="?sort=-active&when={{ when }}&search_input={{ search_input|urlencode }}" class="link-tab {% if table.order_by|safe == '-active' %}link-tab-active{% endif %}">
            <i class="fa fa fa-hand-spock-o" aria-hidden="true"></i> Aktywne
        </a>
        <a href="?sort=-popular&when={{ when }}&search_input={{ search_input|urlencode }}" class="link-tab {% if table.order_by|safe == '-popular' %}link-tab-active{% endif %}">
            <i class="fa fa fa-hand-scissors-o" aria-hidden="true"></i> Popularne
        </a>
    </div>
{% endblock %}

{% block search_content_sidebar_left %}
    <div class="col-xs-12 text-muted text_with_line">Szukaj</div>
    <div class="col-xs-12">
        <form action="" method="GET">
            <div class="form-group has-success">
                <label class="sr-only control-label" for="id_search_input">
                    Co cię interesuje? @użytkownik, #tag lub treść czy tytuł
                </label>
                <input class="form-control" id="id_search_input" maxlength="100" name="search_input" placeholder="Co cię interesuje? @użytkownik, #tag" title="" type="text" value="{{ search_input|safe }}">
            </div>
            <input type="hidden" name="sort" value="{{ how }}">
            <input type="hidden" name="when" value="{{ when }}">
            <button type="submit" class="btn btn-primary pull-right">Szukaj</button>
        </form>
    </div>
    {% if sympathizers %}
        <div class="col-xs-12 text-muted text_with_line">Tagi sympatyków</div>
        <div class="col-xs-12">
            {% for sympathizer in sympathizers %}
                {% render_sympathizer_preview_more sympathizer %}
            {% endfor %}
        </div>
    {% endif %}
    {% if tags %}
        <div class="col-xs-12 text-muted text_with_line">Tagi</div>
        <div class="col-xs-12">
            {% for tag in tags %}
                {% render_tag_preview_more tag %}
            {% endfor %}
        </div>
    {% endif %}

    {% block find_content %}
    {% endblock %}
{% endblock %}

{% block content_sidebar_right %}
    <div class="col-xs-12 text-muted text_with_line">Gdzie</div>
    <div class="col-xs-12">
        <a href="{% url 'search:search_mixed_eureka' %}?sort={{ how }}&when={{ when }}&search_input={{ search_input|urlencode }}" class="link-tab {% if where == 'eureka' %}link-tab-active{% endif %}">Główna</a><br/>
        <a href="{% url 'search:search_mixed_eureka_waiting' %}?sort={{ how }}&when={{ when }}&search_input={{ search_input|urlencode }}" class="link-tab {% if where == 'eureka_waiting' %}link-tab-active{% endif %}">Poczekalnia</a><br/>
        <a href="{% url 'search:search_mixed_concept' %}?sort={{ how }}&when={{ when }}&search_input={{ search_input|urlencode }}" class="link-tab {% if where == 'concept' %}link-tab-active{% endif %}">Koncepcje</a><br/>
        <a href="{% url 'search:search_mixed_everywhere' %}?sort={{ how }}&when={{ when }}&search_input={{ search_input|urlencode }}" class="link-tab {% if where == 'everywhere' %}link-tab-active{% endif %}">Wszędzie</a><br/>
    </div>
    <div class="col-xs-12 text-muted text_with_line">Kiedy</div>
    <div class="col-xs-12">
        <a href="?sort={{ how }}&when=day&search_input={{ search_input|urlencode }}" class="link-tab {% if when == 'day' %}link-tab-active{% endif %}">Dzień</a><br/>
        <a href="?sort={{ how }}&when=week&search_input={{ search_input|urlencode }}" class="link-tab {% if when == 'week' %}link-tab-active{% endif %}">Tydzień</a><br/>
        <a href="?sort={{ how }}&when=month&search_input={{ search_input|urlencode }}" class="link-tab {% if when == 'month' %}link-tab-active{% endif %}">Miesiąc</a><br/>
        <a href="?sort={{ how }}&when=year&search_input={{ search_input|urlencode }}" class="link-tab {% if when == 'year' %}link-tab-active{% endif %}">Rok</a><br/>
        <a href="?sort={{ how }}&when=eternity&search_input={{ search_input|urlencode }}" class="link-tab {% if when == 'eternity' %}link-tab-active{% endif %}">Wieczność</a>
    </div>
{% endblock %}

eDobromir/search/templates/search_mixed_concept.html
{% extends 'search_mixed.html' %}
{% load static %}
{% load tags_concept %}
{% load eureka_templatetags %}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load trans blocktrans from i18n %}
{% load bootstrap3 %}
{% load tags_concept %}

{% block find_content %}
    <div class="col-xs-12 text-muted text_with_line">Koncepcje <sup>{{ table.data|length }}</sup></div>
    {% for row in table.page.object_list|default:table.rows %}
        {% render_concept_preview_medium_extended row.record %}
        <div class="col-xs-12 text_with_line"></div>
    {% endfor %}
    <div class="col-xs-12">
        {% bootstrap_pagination table.page url=request.get_full_path %}
    </div>
{% endblock %}

eDobromir/search/templates/search_mixed_eureka.html
{% extends 'search_mixed.html' %}
{% load static %}
{% load tags_concept %}
{% load eureka_templatetags %}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load trans blocktrans from i18n %}
{% load bootstrap3 %}
{% load tags_concept %}

{% block find_content %}
    <div class="col-xs-12 text-muted text_with_line">Główna <sup>{{ table.data|length }}</sup></div>
    {% for row in table.page.object_list|default:table.rows %}
        {% render_eureka_preview_big row.record %}
        <div class="col-xs-12 text_with_line"></div>
    {% endfor %}
    <div class="col-xs-12">
        {% bootstrap_pagination table.page url=request.get_full_path %}
    </div>
{% endblock %}

eDobromir/search/templates/search_mixed_eureka_waiting.html
{% extends 'search_mixed.html' %}
{% load static %}
{% load tags_concept %}
{% load eureka_templatetags %}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load trans blocktrans from i18n %}
{% load bootstrap3 %}
{% load tags_concept %}

{% block find_content %}
    <div class="col-xs-12 text-muted text_with_line">Poczekalnia <sup>{{ table.data|length }}</sup></div>
    {% for row in table.page.object_list|default:table.rows %}
        {% render_eureka_preview_big row.record %}
        <div class="col-xs-12 text_with_line"></div>
    {% endfor %}
    <div class="col-xs-12">
        {% bootstrap_pagination table.page url=request.get_full_path %}
    </div>
{% endblock %}

eDobromir/search/templates/search_mixed_everywhere.html
{% extends 'search_mixed.html' %}
{% load static %}
{% load tags_concept %}
{% load eureka_templatetags %}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load trans blocktrans from i18n %}
{% load bootstrap3 %}
{% load tags_concept %}

{% block find_content %}
    <div class="col-xs-12 text-muted text_with_line">Główna <sup>{{ table_eureka.data|length }}</sup></div>
    {% for row in table_eureka.page.object_list|default:table_eureka.rows %}
        {% render_eureka_preview_big row.record %}
        {% if not forloop.last %}
            <div class="col-xs-12 text_with_line"></div>
        {% endif %}
    {% endfor %}

    <div class="col-xs-12 text-muted text_with_line">Poczekalnia <sup>{{ table_eureka_waiting.data|length }}</sup></div>
    {% for row in table_eureka_waiting.page.object_list|default:table_eureka_waiting.rows %}
        {% render_eureka_preview_big row.record %}
        {% if not forloop.last %}
            <div class="col-xs-12 text_with_line"></div>
        {% endif %}
    {% endfor %}

    <div class="col-xs-12 text-muted text_with_line">Koncepcje <sup>{{ table_concept.data|length }}</sup></div>
    {% for row in table_concept.page.object_list|default:table_concept.rows %}
        {% render_concept_preview_medium_extended row.record %}
        {% if not forloop.last %}
            <div class="col-xs-12 text_with_line"></div>
        {% endif %}
    {% endfor %}
    <div class="col-xs-12">
    {% if table_eureka.data|length > table_eureka_waiting.data|length %}
        {% if table_eureka.data|length > table_concept.data|length %}
            {% bootstrap_pagination table_eureka.page url=request.get_full_path %}
        {% else %}
            {% bootstrap_pagination table_concept.page url=request.get_full_path %}
        {% endif %}
    {% else %}
        {% if table_eureka_waiting.data|length > table_concept.data|length %}
            {% bootstrap_pagination table_eureka_waiting.page url=request.get_full_path %}
        {% else %}
            {% bootstrap_pagination table_concept.page url=request.get_full_path %}
        {% endif %}
    {% endif %}

    </div>
{% endblock %}