eDobromir/eDobromir/urls.py
from ckeditor_uploader import views as ckeditor_views
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.sitemaps.views import sitemap

from profile_account import urls as profile_accounts_urls
from comments import urls as comments_urls
from errors import urls as errors_urls
from eureka import urls as eureka_urls
from search import urls as search_urls
from votes import urls as vote_urls
from content import urls as content_urls
from concept import urls as concept_urls
from tags import urls as tags_urls
from linked import urls as linked_urls
from moderation import urls as moderation_urls
from notification import urls as notification_urls
from favorites import urls as favorites_urls
import sitemaps as sitemaps_urls
import rss as rss_urls


urlpatterns = [
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^panel/sterowania/swiatem/', include(admin.site.urls)),  # admin site

    url(r'^', include(search_urls, namespace='search')),
    url(r'^', include(eureka_urls, namespace='eureka')),
    url(r'^', include(errors_urls, namespace='errors')),
    url(r'^', include(vote_urls, namespace='votes')),
    url(r'^', include(comments_urls,  namespace='comments')),
    url(r'^', include(content_urls,  namespace='content')),
    url(r'^', include(concept_urls,  namespace='concept')),
    url(r'^', include(tags_urls,  namespace='tags')),
    url(r'^', include(linked_urls,  namespace='linked')),
    url(r'^', include(moderation_urls,  namespace='moderation')),
    url(r'^', include(notification_urls,  namespace='notification')),
    url(r'^', include(favorites_urls,  namespace='favorites')),
    url(r'^', include(profile_accounts_urls)),
    url(r'^', include(sitemaps_urls)),
    url(r'^', include(rss_urls)),

    url(r'^ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    url(r'^ckeditor/browse/', login_required(ckeditor_views.browse), name='ckeditor_browse'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

eDobromir/tags/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *


urlpatterns = [
    url(r'^tag/list/$', TagListView.as_view(), name='tag_list'),
    url(r'^sympathizer/list/$', SympathizerListView.as_view(), name='sympathizer_list'),
    url(r'^sympathizer/create/$', SympathizerCreateView.as_view(), name='sympathizer_create'),
]

eDobromir/votes/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *


urlpatterns = [
    url(r'^eureka/(?P<slug>[-\w]+)/votes/$', VoteDetailEurekaView.as_view(), name='vote_detail_eureka'),
    url(r'^eureka/(?P<slug>[-\w]+)/votes/up/$', VoteUpEurekaView.as_view(), name='vote_up_eureka'),
    url(r'^eureka/(?P<slug>[-\w]+)/votes/delete/$', VoteDownEurekaView.as_view(), name='vote_down_eureka'),

    url(r'^eureka/(?P<slug>[-\w]+)/comments/(?P<comment_slug>[-\w]+)/votes/up/$', VoteUpEurekaCommentView.as_view(), name='vote_up_eureka_comment'),
    url(r'^eureka/(?P<slug>[-\w]+)/comments/(?P<comment_slug>[-\w]+)/votes/delete/$', VoteDownEurekaCommentView.as_view(), name='vote_down_eureka_comment'),

    url(r'^eureka/(?P<slug>[-\w]+)/links/(?P<linked_slug>[-\w]+)/votes/up/$', VoteUpEurekaLinkedView.as_view(), name='vote_up_eureka_linked'),
    url(r'^eureka/(?P<slug>[-\w]+)/links/(?P<linked_slug>[-\w]+)/votes/delete/$', VoteDownEurekaLinkedView.as_view(), name='vote_down_eureka_linked'),

    url(r'^concept/(?P<slug>[-\w]+)/votes/$', VoteDetailConceptView.as_view(), name='vote_detail_concept'),
    url(r'^concept/(?P<slug>[-\w]+)/votes/up/$', VoteUpConceptView.as_view(), name='vote_up_concept'),
    url(r'^concept/(?P<slug>[-\w]+)/votes/delete/$', VoteDownConceptView.as_view(), name='vote_down_concept'),

    url(r'^concept/(?P<slug>[-\w]+)/comments/(?P<comment_slug>[-\w]+)/votes/up/$', VoteUpConceptCommentView.as_view(), name='vote_up_concept_comment'),
    url(r'^concept/(?P<slug>[-\w]+)/comments/(?P<comment_slug>[-\w]+)/votes/delete/$', VoteDownConceptCommentView.as_view(), name='vote_down_concept_comment'),

    url(r'^concept/(?P<slug>[-\w]+)/links/(?P<linked_slug>[-\w]+)/votes/up/$', VoteUpConceptLinkedView.as_view(), name='vote_up_concept_linked'),
    url(r'^concept/(?P<slug>[-\w]+)/links/(?P<linked_slug>[-\w]+)/votes/delete/$', VoteDownConceptLinkedView.as_view(), name='vote_down_concept_linked'),

]

eDobromir/votes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django_extensions.db.models import TimeStampedModel
from sortedm2m.fields import SortedManyToManyField
from vote.models import VoteModel

eDobromir/votes/views.py
# -*- coding: utf-8 -*-

from administration.views import RatelimitVoteActionView
from notification.views import *


class VoteDetailView(DetailView):
    def get_context_data(self, **kwargs):
        contex = super(VoteDetailView, self).get_context_data(**kwargs)
        contex['was_voting'] = self.object.votes.exists(self.request.user.id)
        return contex

    def get_object(self, queryset=None):
        return self.model.objects.get(slug=self.kwargs['slug'])


class VoteDetailEurekaView(VoteDetailView):
    model = Eureka
    template_name = 'vote_eureka.html'


class VoteDetailConceptView(VoteDetailView):
    model = Concept
    template_name = 'vote_concept.html'


class VoteActionView(LoginRequiredMixin, RatelimitVoteActionView, TemplateView):
    vote_object = None
    template_name = ''
    http_method_names = ['post']
    was_voting = None
    raise_exception = True

    def handle_no_permission(self):
        messages.info(self.request, 'Musisz być zalogowany by móc głosować')
        super(VoteActionView, self).handle_no_permission()

    def post(self, request, *args, **kwargs):
        if self.vote_object:
            if not self.vote_object.mask.is_delete:
                self.vote_action()
            else:
                messages.info(self.request, 'Nie możesz głosowac na usunięte treści')
            return render_to_response(self.template_name, context=self.get_context_data(**kwargs))

    def get_context_data(self, **kwargs):
        context = super(VoteActionView, self).get_context_data(**kwargs)
        context['object'] = self.vote_object
        context['was_voting'] = self.was_voting
        context['request'] = self.request
        return context

    def vote_action(self):
        pass

    def get_vote_object(self):
        return self.vote_object

    def success_vote(self):
        pass


class VoteUpView(VoteActionView):
    can_vote = True

    def vote_action(self):
        if self.vote_object.created_by == self.request.user:
            self.can_vote = False

        self.was_voting = self.vote_object.votes.exists(self.request.user.id)
        if self.was_voting:
            self.can_vote = False

        if self.can_vote:
            self.was_voting = True
            self.vote_object.votes.up(self.request.user.id)
            self.vote_object.created_by.rank.up()
            self.success_vote()



class VoteUpEurekaView(VoteUpView, NotificationBehaviorAction):
    template_name = 'vote_eureka.html'

    def dispatch(self, request, *args, **kwargs):
        self.vote_object = get_object_or_404(Eureka, slug=kwargs['slug'])
        self.notification_target = self.vote_object.created_by
        self.notification_actor = self.vote_object
        return super(VoteUpEurekaView, self).dispatch(request, *args, **kwargs)

    def success_vote(self):
        self.notification_action()


class VoteUpConceptView(VoteUpView):
    template_name = 'vote_concept.html'

    def dispatch(self, request, *args, **kwargs):
        self.vote_object = get_object_or_404(Concept, slug=kwargs['slug'])
        return super(VoteUpConceptView, self).dispatch(request, *args, **kwargs)


class VoteUpEurekaLinkedView(VoteUpView):
    template_name = 'vote_eureka_linked.html'

    def dispatch(self, request, *args, **kwargs):
        eureka = get_object_or_404(Eureka, slug=kwargs['slug'])
        kwargs['eureka'] = eureka
        self.vote_object = eureka.links.get(slug=self.kwargs['linked_slug'])
        return super(VoteUpEurekaLinkedView, self).dispatch(request, *args, **kwargs)


class VoteUpConceptLinkedView(VoteUpView):
    template_name = 'vote_concept_linked.html'

    def dispatch(self, request, *args, **kwargs):
        concept = get_object_or_404(Concept, slug=kwargs['slug'])
        kwargs['concept'] = concept
        self.vote_object = concept.links.get(slug=self.kwargs['linked_slug'])
        return super(VoteUpConceptLinkedView, self).dispatch(request, *args, **kwargs)


class VoteUpEurekaCommentView(VoteUpView):
    template_name = 'vote_eureka_comment.html'

    def dispatch(self, request, *args, **kwargs):
        eureka = get_object_or_404(Eureka, slug=kwargs['slug'])
        kwargs['eureka'] = eureka

        self.vote_object = eureka.comments.get(slug=kwargs['comment_slug'])
        return super(VoteUpEurekaCommentView, self).dispatch(request, *args, **kwargs)


class VoteUpConceptCommentView(VoteUpView):
    template_name = 'vote_concept_comment.html'

    def dispatch(self, request, *args, **kwargs):
        concept = get_object_or_404(Concept, slug=kwargs['slug'])
        kwargs['concept'] = concept

        self.vote_object = concept.comments.get(slug=kwargs['comment_slug'])
        return super(VoteUpConceptCommentView, self).dispatch(request, *args, **kwargs)


class VoteDownView(VoteActionView):
    def vote_action(self):
        self.was_voting = self.vote_object.votes.exists(self.request.user.id)
        if not self.was_voting:
            return

        self.was_voting = False
        self.vote_object.votes.delete(self.request.user.id)
        self.vote_object.created_by.rank.down()


class VoteDownEurekaView(VoteDownView):
    template_name = 'vote_eureka.html'

    def dispatch(self, request, *args, **kwargs):
        self.vote_object = get_object_or_404(Eureka, slug=kwargs['slug'])
        return super(VoteDownEurekaView, self).dispatch(request, *args, **kwargs)


class VoteDownConceptView(VoteDownView):
    template_name = 'vote_concept.html'

    def dispatch(self, request, *args, **kwargs):
        self.vote_object = get_object_or_404(Concept, slug=kwargs['slug'])
        return super(VoteDownConceptView, self).dispatch(request, *args, **kwargs)


class VoteDownEurekaLinkedView(VoteDownView):
    template_name = 'vote_eureka_linked.html'

    def dispatch(self, request, *args, **kwargs):
        eureka = get_object_or_404(Eureka, slug=kwargs['slug'])
        kwargs['eureka'] = eureka
        self.vote_object = eureka.links.get(slug=self.kwargs['linked_slug'])
        return super(VoteDownEurekaLinkedView, self).dispatch(request, *args, **kwargs)


class VoteDownConceptLinkedView(VoteDownView):
    template_name = 'vote_concept_linked.html'

    def dispatch(self, request, *args, **kwargs):
        concept = get_object_or_404(Concept, slug=kwargs['slug'])
        kwargs['concept'] = concept
        self.vote_object = concept.links.get(slug=self.kwargs['linked_slug'])
        return super(VoteDownConceptLinkedView, self).dispatch(request, *args, **kwargs)


class VoteDownEurekaCommentView(VoteDownView):
    template_name = 'vote_eureka_comment.html'

    def dispatch(self, request, *args, **kwargs):
        eureka = get_object_or_404(Eureka, slug=kwargs['slug'])
        kwargs['eureka'] = eureka
        self.vote_object = eureka.comments.get(slug=self.kwargs['comment_slug'])
        return super(VoteDownEurekaCommentView, self).dispatch(request, *args, **kwargs)


class VoteDownConceptCommentView(VoteDownView):
    template_name = 'vote_concept_comment.html'

    def dispatch(self, request, *args, **kwargs):
        concept = get_object_or_404(Concept, slug=kwargs['slug'])
        kwargs['concept'] = concept
        self.vote_object = concept.comments.get(slug=self.kwargs['comment_slug'])
        return super(VoteDownConceptCommentView, self).dispatch(request, *args, **kwargs)

eDobromir/votes/templates/vote_base.html
<div class="{% block vote_area_id %}{% endblock %}">
    <strong style="{% block vote_font_size %}{% endblock %}">
        <div class="clearfix row-no-padding">
            <div class="col-xs-12">
                <a href="{% if not object.mask.is_delete %}{% if not was_voting %}{% block vote_up_url %}{% endblock %}{% else %}{% block vote_down_url %}{% endblock %}{% endif %}{% else %}#{% endif %}" class="link-tab {% if was_voting %}link-tab-active{% endif %} {% if not object.mask.is_delete %}ajax_link{% endif %}" data-id="{% if not was_voting %}{% block vote_up_link_id %}{% endblock %}{% else %}{% block vote_down_link_id %}{% endblock %}{% endif %}">
                    {% block vote_up_icon %}
                    {% endblock %}
                </a>
            </div>
            <div class="col-xs-12" style="{% block vote_count_font_size %}{% endblock %}">
                {% block vote_count %}
                    {{ object.votes.count }}
                {% endblock %}
            </div>
            <div class="col-xs-12">
                {% block vote_down %}
                {% endblock %}
            </div>
        </div>
    </strong>
</div>

eDobromir/votes/templates/vote_concept.html
{% extends 'vote_concept_base.html' %}

{% block vote_font_size %}font-size: 45px;{% endblock %}

{% block vote_count_font_size %}font-size: 25px;{% endblock %}

{% block vote_area_id %}vote_concept_{{ object.slug }}{% endblock %}

{% block vote_up_url %}{% url 'votes:vote_up_concept' object.slug %}{% endblock %}

{% block vote_down_url %}{% url 'votes:vote_down_concept' object.slug %}{% endblock %}

{% block vote_up_link_id %}vote_concept_{{ object.slug }}{% endblock %}

{% block vote_down_link_id %}vote_concept_{{ object.slug }}{% endblock %}

eDobromir/votes/templates/vote_concept_base.html
{% extends 'vote_base.html' %}
{% load moderation_templatetags %}

{% block vote_up_icon %}
    <i class="fa fa-circle-o" aria-hidden="true"></i>
{% endblock %}

eDobromir/votes/templates/vote_concept_comment.html
{% extends 'vote_concept_base.html' %}
{% load moderation_templatetags %}

{% block vote_area_id %}vote_concept_comment_{{ object.slug }}{% endblock %}

{% block vote_up_url %}{% url 'votes:vote_up_concept_comment' concept.slug object.slug %}{% endblock %}

{% block vote_down_url %}{% url 'votes:vote_down_concept_comment' concept.slug object.slug %}{% endblock %}

{% block vote_up_link_id %}vote_concept_comment_{{ object.slug }}{% endblock %}

{% block vote_down_link_id %}vote_concept_comment_{{ object.slug }}{% endblock %}

{% block vote_count %}{% endblock %}

{% block vote_up_icon %}
    <i class="fa fa-chevron-up" aria-hidden="true"></i>
{% endblock %}

eDobromir/votes/templates/vote_concept_linked.html
{% extends 'vote_concept_base.html' %}
{% load moderation_templatetags %}

{% block vote_area_id %}vote_concept_linked_{{ object.slug }}{% endblock %}

{% block vote_up_url %}{% url 'votes:vote_up_concept_linked' concept.slug object.slug %}{% endblock %}

{% block vote_down_url %}{% url 'votes:vote_down_concept_linked' concept.slug object.slug %}{% endblock %}

{% block vote_up_link_id %}vote_concept_linked_{{ object.slug }}{% endblock %}

{% block vote_down_link_id %}vote_concept_linked_{{ object.slug }}{% endblock %}

{% block vote_count %}{% endblock %}

{% block vote_down %}
{% endblock %}

eDobromir/votes/templates/vote_detail.html
{% load bootstrap3 %}
{% load static %}
{% load eureka_templatetags %}
{% load comments_templatetags %}
{% load profile_account_templatetags %}

<p>
    Punktowali <strong>{{ voteObject.votes.count|default:'0' }}</strong>
    <small class="pull-right">
        <a type="button"
                class="vote_detail_link link-tab"
                data-toggle="modal"
                data-target="#vote_detail_modal">
            <i class="fa fa-eye" aria-hidden="true"></i> Pokaż
        </a>
    </small>
</p>

<div class="modal" id="vote_detail_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Użytkownik</th>
                            <th>Dzień</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for vote in voteObject.votes.user_ids %}
                            <tr>
                                <td>{% render_profile_username vote.0 %}</td>
                                <td>{{ vote.1 }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
            </div>
        </div>
    </div>
</div>

eDobromir/votes/templates/vote_eureka.html
{% extends 'vote_eureka_base.html' %}

{% block vote_font_size %}font-size: 45px;{% endblock %}
{% block vote_count_font_size %}font-size: 25px;{% endblock %}

{% block vote_area_id %}vote_eureka_{{ object.slug }}{% endblock %}

{% block vote_up_url %}{% url 'votes:vote_up_eureka' object.slug %}{% endblock %}
{% block vote_down_url %}{% url 'votes:vote_down_eureka' object.slug %}{% endblock %}

{% block vote_up_link_id %}vote_eureka_{{ object.slug }}{% endblock %}
{% block vote_down_link_id %}vote_eureka_{{ object.slug }}{% endblock %}

eDobromir/votes/templates/vote_eureka_base.html
{% extends 'vote_base.html' %}

{% load moderation_templatetags %}

{% block vote_up_icon %}
    <i class="fa fa-lightbulb-o" aria-hidden="true"></i>
{% endblock %}

eDobromir/votes/templates/vote_eureka_comment.html
{% extends 'vote_eureka_base.html' %}
{% load moderation_templatetags %}

{% block vote_area_id %}vote_eureka_comment_{{ object.slug }}{% endblock %}

{% block vote_up_url %}{% url 'votes:vote_up_eureka_comment' eureka.slug object.slug %}{% endblock %}

{% block vote_down_url %}{% url 'votes:vote_down_eureka_comment' eureka.slug object.slug %}{% endblock %}

{% block vote_up_link_id %}vote_eureka_comment_{{ object.slug }}{% endblock %}

{% block vote_down_link_id %}vote_eureka_comment_{{ object.slug }}{% endblock %}

{% block vote_count %}{% endblock %}

{% block vote_up_icon %}
    <i class="fa fa-chevron-up" aria-hidden="true"></i>
{% endblock %}

eDobromir/votes/templates/vote_eureka_linked.html
{% extends 'vote_eureka_base.html' %}

{% block vote_area_id %}vote_eureka_linked_{{ object.slug }}{% endblock %}

{% block vote_up_url %}{% url 'votes:vote_up_eureka_linked' eureka.slug object.slug %}{% endblock %}

{% block vote_down_url %}{% url 'votes:vote_down_eureka_linked' eureka.slug object.slug %}{% endblock %}

{% block vote_up_link_id %}vote_eureka_linked_{{ object.slug }}{% endblock %}

{% block vote_down_link_id %}vote_eureka_linked_{{ object.slug }}{% endblock %}

{% block vote_count %}{% endblock %}

{% block vote_down %}
{% endblock %}