eDobromir/eDobromir/urls.py
from ckeditor_uploader import views as ckeditor_views
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.sitemaps.views import sitemap

from profile_account import urls as profile_accounts_urls
from comments import urls as comments_urls
from errors import urls as errors_urls
from eureka import urls as eureka_urls
from search import urls as search_urls
from votes import urls as vote_urls
from content import urls as content_urls
from concept import urls as concept_urls
from tags import urls as tags_urls
from linked import urls as linked_urls
from moderation import urls as moderation_urls
from notification import urls as notification_urls
from favorites import urls as favorites_urls
import sitemaps as sitemaps_urls
import rss as rss_urls


urlpatterns = [
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^panel/sterowania/swiatem/', include(admin.site.urls)),  # admin site

    url(r'^', include(search_urls, namespace='search')),
    url(r'^', include(eureka_urls, namespace='eureka')),
    url(r'^', include(errors_urls, namespace='errors')),
    url(r'^', include(vote_urls, namespace='votes')),
    url(r'^', include(comments_urls,  namespace='comments')),
    url(r'^', include(content_urls,  namespace='content')),
    url(r'^', include(concept_urls,  namespace='concept')),
    url(r'^', include(tags_urls,  namespace='tags')),
    url(r'^', include(linked_urls,  namespace='linked')),
    url(r'^', include(moderation_urls,  namespace='moderation')),
    url(r'^', include(notification_urls,  namespace='notification')),
    url(r'^', include(favorites_urls,  namespace='favorites')),
    url(r'^', include(profile_accounts_urls)),
    url(r'^', include(sitemaps_urls)),
    url(r'^', include(rss_urls)),

    url(r'^ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    url(r'^ckeditor/browse/', login_required(ckeditor_views.browse), name='ckeditor_browse'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

eDobromir/eureka/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *


urlpatterns = [
    url(r'^eureka/create/$', EurekaCreateView.as_view(), name='eureka_create'),
    url(r'^eureka/(?P<slug>[-\w]+)/update/$', EurekaUpdateView.as_view(), name='eureka_update'),
    url(r'^eureka/(?P<slug>[-\w]+)/delete/$', EurekaDeleteView.as_view(), name='eureka_delete'),
    url(r'^eureka/(?P<slug>[-\w]+)/$', EurekaDetailView.as_view(), name='eureka_detail'),
    url(r'^eureka/(?P<slug>[-\w]+)/summary/$', EurekaSummaryView.as_view(), name='eureka_summary'),

    url(r'^eureka/(?P<slug>[-\w]+)/instruction/$', EurekaInstructionDetailView.as_view(), name='eureka_instruction_detail'),
    url(r'^eureka/(?P<slug>[-\w]+)/instruction/step/create/', EurekaInstructionStepCreateView.as_view(), name='eureka_instruction_step_create'),
    url(r'^eureka/(?P<slug>[-\w]+)/instruction/step/(?P<step_slug>[-\w]+)/update/', EurekaInstructionStepUpdateView.as_view(), name='eureka_instruction_step_update'),
    url(r'^eureka/(?P<slug>[-\w]+)/instruction/step/(?P<step_slug>[-\w]+)/delete/', EurekaInstructionStepDeleteView.as_view(), name='eureka_instruction_step_delete'),

]

eDobromir/tags/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *


urlpatterns = [
    url(r'^tag/list/$', TagListView.as_view(), name='tag_list'),
    url(r'^sympathizer/list/$', SympathizerListView.as_view(), name='sympathizer_list'),
    url(r'^sympathizer/create/$', SympathizerCreateView.as_view(), name='sympathizer_create'),
]

eDobromir/eureka/forms.py
# -*- coding: utf-8 -*-

from .models import Eureka
from django import forms
from fontawesome.utils import get_icon_choices
from django.contrib import messages
from tags.models import Sympathizer
import urllib
from BeautifulSoup import BeautifulSoup
import json
import os
from django.conf import settings
from django.template.defaultfilters import slugify


# CHOICES = Sympathizer.objects.all().values_list('id', 'name') or None
#
#
# class SympathizerEurekaIconWidget(forms.Select):
#     def create_option(self, name, value, label, selected, index, subindex=None, attrs=None):
#         option = super(SympathizerEurekaIconWidget, self).create_option(name, value, label, selected, index, subindex=None, attrs=None)
#         option['attrs'] = {'data-icon': Sympathizer.objects.get(id=value).icon}
#         return option


class EurekaCreateForm(forms.ModelForm):
    # sympathizers = forms.IntegerField(widget=SympathizerEurekaIconWidget(choices=CHOICES), required=False, label='Sympatycy')
    #
    # def clean_sympathizers(self):
    #     data = self.cleaned_data['sympathizers']
    #     data = Sympathizer.objects.get(id=data)
    #     return data
    preview_image = forms.ImageField(required=False, label='Miniaturka (nie wymagana, jeśli dodany jest link doda się automatycznie)')

    def clean_preview_image(self):
        data = self.cleaned_data['preview_image']
        link = self.cleaned_data['link']
        embed_link = 'https://www.iframe.ly/api/oembed?url=' + link + '&api_key=c3e45645472c7d510319ab'
        if data:
            return data
        elif link:
            content = urllib.urlopen(embed_link).read()
            json_data = json.loads(content)
            file_link = json_data['thumbnail_url']

            if not file_link:
                return 'preview_images/default-no-image.png'
            else:
                link_name = link.split('/')[-1]
                file_name = file_link.split('/')[-1]
                final_file_name = slugify(link_name.replace('/', '') + file_name.replace('/', '')) + '.' + file_name.split('.')[-1]
                urllib.urlretrieve(file_link, os.path.join(settings.MEDIA_ROOT + '/preview_images/', os.path.basename(final_file_name)))
                return 'preview_images/' + final_file_name
        else:
            return 'preview_images/default-no-image.png'

    class Meta:
        model = Eureka
        fields = ['title', 'tags', 'sympathizers', 'description', 'link', 'content_type', 'preview_image', 'difficult', 'price']

eDobromir/eureka/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from .models import Eureka, EurekaInstruction, EurekaInstructionStep
from django.core.urlresolvers import reverse_lazy
from django.template.defaultfilters import slugify
import itertools
from guardian.mixins import PermissionRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from guardian.shortcuts import assign_perm, remove_perm
from django.utils import timezone
from django.contrib.auth.models import Group, User
from diary.views import DiaryOpenView
from django.forms.forms import ValidationError
from notification.views import *
from administration.views import RatelimitEurekaCreateView, RatelimitEurekaStepCreateView
from mask.models import DeleteMask
from .forms import EurekaCreateForm


class EurekaCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Eureka
    template_name = 'eureka_create.html'
    form_class = EurekaCreateForm

    permission_object = None
    permission_required = 'eureka.add_eureka'

    def form_valid(self, form):
        tags = form.cleaned_data['tags']
        if len(tags) > 5:
            raise ValidationError('Możesz wprowadzić maksymalnie 5 tagów.')

        max_length_slug = Eureka._meta.get_field('slug').max_length
        slug = orig = slugify(form.instance.title)[0:max_length_slug]
        for x in itertools.count(1):
            if not Eureka.objects.filter(slug=slug).exists():
                break
            slug = "%s-%d" % (orig[:max_length_slug - len(str(x)) - 1], x)

        form.instance.slug = slug
        form.instance.created_by = self.request.user
        form.instance.eurekaInstruction = EurekaInstruction.objects.create()
        form.instance.mask = DeleteMask.objects.create()
        return super(EurekaCreateView, self).form_valid(form)

    def get_success_url(self):
        assign_perm('eureka.is_owner', self.object.created_by, self.object)
        assign_perm('eureka.can_view', self.object.created_by, self.object)
        assign_perm('eureka.change_eureka', self.object.created_by, self.object)
        assign_perm('eureka.delete_eureka', self.object.created_by, self.object)
        return reverse_lazy('eureka:eureka_summary', kwargs={'slug':self.object.slug})


class EurekaUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Eureka
    fields = ['title', 'tags', 'sympathizers', 'description', 'link', 'preview_image', 'price', 'difficult', 'content_type']
    template_name = 'eureka_update.html'
    permission_required = 'eureka.change_eureka'
    raise_exception = True

    def get_success_url(self):
        return reverse_lazy('eureka:eureka_summary', kwargs={'slug':self.object.slug})


class EurekaDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Eureka
    template_name = 'eureka_delete.html'
    permission_required = 'eureka.delete_eureka'
    raise_exception = True

    def get_permission_object(self):
        return self.get_object()

    def get_success_url(self):
        return reverse_lazy('search:search_eureka')


class EurekaDetailView(PermissionRequiredMixin, DiaryOpenView):
    model = Eureka
    template_name = 'eureka_detail.html'
    permission_required = 'eureka.can_view'
    raise_exception = True

    def get_context_data(self, **kwargs):
        kwargs['active_page'] = 'eureka_detail'
        kwargs['eureka'] = self.object
        kwargs['order_by'] = self.request.GET.get('order_by')
        return kwargs


class EurekaInstructionDetailView(PermissionRequiredMixin, DetailView):
    model = Eureka
    template_name = 'eureka_instruction.html'
    permission_required = 'eureka.can_view'
    raise_exception = True

    def get_context_data(self, **kwargs):
        kwargs['eureka'] = self.object
        kwargs['active_page'] = 'eureka_instruction_detail'
        return kwargs


class EurekaInstructionStepCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = EurekaInstructionStep
    fields = ['title', 'content']
    template_name = 'eureka_instruction_step_create.html'
    eureka = None
    permission_required = 'eureka.change_eureka'
    raise_exception = True

    def get_permission_object(self):
        return self.eureka

    def dispatch(self, request, *args, **kwargs):
        self.eureka = Eureka.objects.get(slug=kwargs['slug'])
        return super(EurekaInstructionStepCreateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(EurekaInstructionStepCreateView, self).get_context_data(**kwargs)
        context['eureka'] = self.eureka
        return context

    def form_valid(self, form):
        all_steps = self.eureka.eurekaInstruction.steps.all()
        max_length_slug = EurekaInstructionStep._meta.get_field('step_slug').max_length
        step_slug = orig = slugify(form.instance.title)[0:max_length_slug]
        for x in itertools.count(1):
            if not all_steps.filter(step_slug=step_slug).exists():
                break
            step_slug = "%s-%d" % (orig[:max_length_slug - len(str(x)) - 1], x)

        form.instance.step_slug = step_slug
        return super(EurekaInstructionStepCreateView, self).form_valid(form)

    def get_success_url(self):
        self.eureka.eurekaInstruction.steps.add(self.object)
        return reverse_lazy('eureka:eureka_instruction_step_update', kwargs={'slug':self.eureka.slug, 'step_slug': self.object.step_slug})


class EurekaInstructionStepUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = EurekaInstructionStep
    fields = ['title', 'content']
    template_name = 'eureka_instruction_step_update.html'
    eureka = None
    permission_required = 'eureka.change_eureka'
    raise_exception = True

    def get_permission_object(self):
        return self.eureka

    def dispatch(self, request, *args, **kwargs):
        self.eureka = Eureka.objects.get(slug=kwargs['slug'])
        return super(EurekaInstructionStepUpdateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(EurekaInstructionStepUpdateView, self).get_context_data(**kwargs)
        context['eureka'] = self.eureka
        return context

    def get_object(self, queryset=None):
        step_slug = self.kwargs['step_slug']
        return EurekaInstructionStep.objects.get(step_slug=step_slug, eurekainstruction=self.eureka.eurekaInstruction)

    def get_success_url(self):
        return reverse_lazy('eureka:eureka_instruction_step_update', kwargs={'slug':self.eureka.slug, 'step_slug': self.object.step_slug})

    def form_valid(self, form):
        all_steps = self.eureka.eurekaInstruction.steps.all()
        max_length_slug = EurekaInstructionStep._meta.get_field('step_slug').max_length
        step_slug = orig = slugify(form.instance.title)[0:max_length_slug]
        for x in itertools.count(1):
            if not all_steps.filter(step_slug=step_slug).exists():
                break
            step_slug = "%s-%d" % (orig[:max_length_slug - len(str(x)) - 1], x)

        form.instance.step_slug = step_slug
        return super(EurekaInstructionStepUpdateView, self).form_valid(form)


class EurekaInstructionStepDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = EurekaInstructionStep
    fields = ['title']
    template_name = 'eureka_instruction_step_delete.html'
    eureka = None
    permission_required = 'eureka.change_eureka'
    raise_exception = True

    def get_permission_object(self):
        return self.eureka

    def dispatch(self, request, *args, **kwargs):
        self.eureka = Eureka.objects.get(slug=kwargs['slug'])
        return super(EurekaInstructionStepDeleteView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(EurekaInstructionStepDeleteView, self).get_context_data(**kwargs)
        context['eureka'] = self.eureka
        return context

    def get_object(self, queryset=None):
        step_slug = self.kwargs['step_slug']
        return EurekaInstructionStep.objects.get(step_slug=step_slug, eurekainstruction=self.eureka.eurekaInstruction)

    def get_success_url(self):
        return reverse_lazy('eureka:eureka_instruction_step_create', kwargs={'slug':self.eureka.slug})


class EurekaSummaryView(LoginRequiredMixin, PermissionRequiredMixin, NotificationNewContentAction, UpdateView):
    model = Eureka
    fields = ['is_published']
    template_name = 'eureka_summary.html'
    permission_required = 'eureka.is_owner'
    raise_exception = True

    def form_valid(self, form):
        form.instance.is_published = True
        form.instance.published = timezone.now()
        users_group = get_object_or_404(Group, name='users')
        anonymous_users = get_object_or_404(User, username='AnonymousUser')
        assign_perm('eureka.can_vote', users_group, self.object)
        assign_perm('eureka.can_view', users_group, self.object)
        assign_perm('eureka.can_view', anonymous_users, self.object)
        return super(EurekaSummaryView, self).form_valid(form)

    def get_success_url(self):
        self.notification_actor = self.object
        self.notification_action()
        return reverse_lazy('eureka:eureka_summary', kwargs={'slug': self.object.slug})

eDobromir/eureka/templates/eureka_base.html
{% extends 'dashboard_sidebar_info.html' %}
{% load static %}
{% load imagekit %}
{% load eureka_templatetags %}
{% load comments_templatetags %}

{% block title %}{{ eureka.title }}{% endblock %}

{% block info_content_sidebar_top %}
    <div class="col-xs-12">
        <a href="{% url 'eureka:eureka_detail' eureka.slug %}" class="link-tab {% if active_page == 'eureka_detail' %}link-tab-active{% endif %}"><i class="fa fa-comments" aria-hidden="true"></i> Komentarze</a>
        {% if eureka.eurekaInstruction.steps.count > 0 %}
            <a href="{% url 'eureka:eureka_instruction_detail' eureka.slug %}" class="btn {% if active_page == 'eureka_detail' %}btn-default{% else %}btn-primary{% endif %}"><i class="fa fa-list-ol" aria-hidden="true"></i> Przejdź do instrukcji <span class="badge">{{ eureka.eurekaInstruction.steps.count }}</span></a>
        {% endif %}
        {% if eureka.link %}
            <a href="{{ eureka.link }}" class="btn btn-default"><i class="fa fa-external-link" aria-hidden="true"></i></a>
        {% endif %}
    </div>
{% endblock %}

eDobromir/eureka/templates/eureka_delete.html
{% extends 'dashboard_sidebar_recent.html' %}
{% load static %}
{% load imagekit %}
{% load bootstrap3 %}
{% load eureka_templatetags %}

{% block title %}Usuń eurekę{% endblock %}

{% block recent_content_sidebar_left %}
    <div class="col-md-12 text-muted text_with_line">Usuwanie eureki</div>
    <div class="col-xs-12">
        {% render_eureka_preview_big object %}
        <form action="" method="post">
            {% csrf_token %}
            <button class="btn btn-danger pull-right" type="submit">Usuń eurekę</button>
        </form>
    </div>
{% endblock %}

eDobromir/eureka/templates/eureka_instruction_step_update.html
{% extends 'eureka_instruction_step_base.html' %}

{% load static %}
{% load imagekit %}
{% load bootstrap3 %}

{% block step_content_sidebar_left %}
    <div class="col-md-12 text-muted text_with_line">Aktualizuj krok</div>
    <div class="col-xs-12">
        <form action="" method="post" id="step_update">
            {% csrf_token %}
            {% bootstrap_field form.title %}
            {% bootstrap_field form.content %}
        </form>

        <div class="btn-group pull-right">
            <a href="{% url 'eureka:eureka_instruction_step_delete' slug=eureka.slug step_slug=object.step_slug %}" class="btn btn-danger">Usuń</a>
            <button type="submit" class="btn btn-primary" form="step_update">Aktualizuj</button>
        </div>
    </div>
{% endblock %}

eDobromir/eureka/templates/eureka_preview_big.html
{% load tags_vote %}
{% load tags_templatetags %}
{% load moderation_templatetags %}
{% load profile_account_templatetags %}
{% load notification_templatetags %}
{% load favorites_templatetags %}

<div class="col-xs-12">
    <div class="clearfix row-no-padding">
        <div class="col-sm-1 col-xs-2 text-center">
            <div style="padding-right: 10px;" class="vote_body">
                {% autoescape off %}
                {% render_vote_eureka eureka %}
                {% endautoescape %}
            </div>
        </div>
        <div class="col-sm-3 col-xs-10">
            <a href="{% url 'eureka:eureka_detail' eureka.slug %}" class="link-remove-format link-tab"><img src="{{ eureka.preview_image_thumbnail.url }}" class="img-responsive"></a>
        </div>
        <div class="col-sm-8 col-xs-10">
            <div style="padding-left: 10px;">
                <strong style="font-size: 18px;"><a href="{% url 'eureka:eureka_detail' eureka.slug %}" class="link-remove-format">{{ eureka.title }}</a></strong>
                <p>
                    <small class="text-muted">
                        @{% render_profile_username eureka.created_by %}
                        {% if eureka.sympathizers %}
                            {% render_sympathizer_preview_less eureka.sympathizers.name %}
                        {% endif %}
                        {% for tag in eureka.tags.all %}
                            {% render_tag_preview_less tag %}
                        {% endfor %}
                        <i class="fa fa-comments" aria-hidden="true"></i> {{ eureka.comments.count }}
                        <i class="fa fa-calendar" aria-hidden="true"></i>
                        {% if eureka.published %}
                            {{ eureka.published|date }}
                        {% else %}
                            Nie opublikowano
                        {% endif %}
                    </small>
                </p>
                <p>{{ eureka.description }}</p>
                <p>
                    <small class="text-muted">
                        {% render_notification_followers eureka.created_by %}
                        {% render_favorites_manager_eureka eureka %}
                        {% render_moderation_report_eureka_create eureka %}

                        {% if eureka.created_by == request.user %}
                            <a href="{% url 'eureka:eureka_delete' eureka.slug %}" class="link-tab"><i class="fa fa-trash-o" aria-hidden="true"></i> Usuń</a>
                            <a href="{% url 'eureka:eureka_summary' eureka.slug %}" class="link-tab"><i class="fa fa-list-alt" aria-hidden="true"></i> Zarządzaj</a>
                        {% endif %}

                        <span class="pull-right">
                            {% if eureka.price %}
                                <span class="label label-primary">{{ eureka.price }} zł</span>
                            {% endif %}
                            {% if eureka.difficult %}
                                {% if eureka.difficult == 'easy' %}
                                    <span class="label label-success">Łatwy</span>
                                {% else %}
                                    {% if eureka.difficult == 'medium' %}
                                        <span class="label label-warning">Średni</span>
                                    {% else %}
                                        <span class="label label-danger">Trudny</span>
                                    {% endif %}
                                {% endif %}
                            {% endif %}
                        </span>
                    </small>
                </p>
            </div>
        </div>
    </div>
</div>

eDobromir/eureka/templates/eureka_preview_big_link_to_instruction.html
{% load tags_vote %}
{% load tags_templatetags %}
{% load moderation_templatetags %}
{% load profile_account_templatetags %}
{% load notification_templatetags %}
{% load favorites_templatetags %}

<div class="col-xs-12">
    <div class="clearfix row-no-padding">
        <div class="col-sm-1 col-xs-2 text-center">
            <div style="padding-right: 10px;" class="vote_body">
                {% autoescape off %}
                {% render_vote_eureka eureka %}
                {% endautoescape %}
            </div>
        </div>
        <div class="col-sm-3 col-xs-10">
            <a href="{% if eureka.link %}{{ eureka.link }}{% else %}{% url 'eureka:eureka_instruction_detail' eureka.slug %}{% endif %}" class="link-remove-format link-tab"><img src="{{ eureka.preview_image_thumbnail.url }}" class="img-responsive"></a>
        </div>
        <div class="col-sm-8 col-xs-10">
            <div style="padding-left: 10px;">
                <strong style="font-size: 18px;"><a href="{% if eureka.link %}{{ eureka.link }}{% else %}{% url 'eureka:eureka_instruction_detail' eureka.slug %}{% endif %}" class="link-remove-format">{{ eureka.title }}</a></strong>
                <p>
                    <small class="text-muted">
                        @{% render_profile_username eureka.created_by %}
                        {% if eureka.sympathizers %}
                            {% render_sympathizer_preview_less eureka.sympathizers.name %}
                        {% endif %}
                        {% for tag in eureka.tags.all %}
                            {% render_tag_preview_less tag %}
                        {% endfor %}
                        <i class="fa fa-comments" aria-hidden="true"></i> {{ eureka.comments.count }}
                        <i class="fa fa-calendar" aria-hidden="true"></i>
                        {% if eureka.published %}
                            {{ eureka.published|date }}
                        {% else %}
                            Nie opublikowano
                        {% endif %}
                    </small>
                </p>
                <p>{{ eureka.description }}</p>
                <p>
                    <small class="text-muted">
                        {% render_notification_followers eureka.created_by %}
                        {% render_favorites_manager_eureka eureka %}
                        {% render_moderation_report_eureka_create eureka %}

                        {% if eureka.created_by == request.user %}
                            <a href="{% url 'eureka:eureka_delete' eureka.slug %}" class="link-tab"><i class="fa fa-trash-o" aria-hidden="true"></i> Usuń</a>
                            <a href="{% url 'eureka:eureka_summary' eureka.slug %}" class="link-tab"><i class="fa fa-list-alt" aria-hidden="true"></i> Zarządzaj</a>
                        {% endif %}

                        <span class="pull-right">
                            {% if eureka.price %}
                                <span class="label label-primary">{{ eureka.price }} zł</span>
                            {% endif %}
                            {% if eureka.difficult %}
                                {% if eureka.difficult == 'easy' %}
                                    <span class="label label-success">Łatwy</span>
                                {% else %}
                                    {% if eureka.difficult == 'medium' %}
                                        <span class="label label-warning">Średni</span>
                                    {% else %}
                                        <span class="label label-danger">Trudny</span>
                                    {% endif %}
                                {% endif %}
                            {% endif %}
                        </span>
                    </small>
                </p>
            </div>
        </div>
    </div>
</div>

eDobromir/eureka/templates/eureka_summary.html
{% extends 'dashboard_sidebar_recent.html' %}
{% load static %}
{% load imagekit %}
{% load bootstrap3 %}
{% load eureka_templatetags %}

{% block title %}Podsumowanie{% endblock %}

{% block recent_content_sidebar_left %}
    <div class="col-xs-12 text-muted text_with_line">
        Eureka
        <span class="pull-right">
            <a href="{% url 'eureka:eureka_update' slug=eureka.slug %}" class="link-tab"><small><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edytuj </small></a>
            <a href="{% url 'eureka:eureka_detail' slug=eureka.slug %}" class="link-tab"><small><i class="fa fa-search" aria-hidden="true"></i> Podgląd</small></a>
        </span>
    </div>
    <div class="col-xs-12">
        {% render_eureka_preview_big eureka %}
    </div>

    <div class="col-xs-12 text-muted text_with_line">
        Instrukcja
        <span class="pull-right">
            <a href="{% url 'eureka:eureka_instruction_step_create' slug=eureka.slug %}" class="link-tab"><small><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edytuj </small></a>
            <a href="{% url 'eureka:eureka_instruction_detail' slug=eureka.slug %}" class="link-tab"><small><i class="fa fa-search" aria-hidden="true"></i> Podgląd</small></a>
        </span>
    </div>
    <div class="col-xs-12">
        <div class="clearfix row-no-padding">
            {% if not eureka.eurekaInstruction.steps.count > 0 %}
                <div class="alert alert-warning">
                    Twoja eureka nie posiada instrukcji, nie jest ona wymagana do jej opublikowania.
                </div>
                <a href="{% url 'eureka:eureka_instruction_step_create' slug=eureka.slug %}" class="btn btn-primary pull-right">Dodaj instrukcję</a>
            {% else %}
                <div class="col-xs-6">
                    <ul class="instruction_nav nav ">
                        {% for step in eureka.eurekaInstruction.steps.all %}
                            <li>
                                <a href="{% url 'eureka:eureka_instruction_step_update' slug=eureka.slug step_slug=step.step_slug %}">Krok {{ forloop.counter }}:  {{ step.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-xs-6">
                    Ilość kroków: {{ eureka.eurekaInstruction.steps.count }}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="col-xs-12 text-muted text_with_line"></div>
    <div class="col-xs-12">
        {% if not eureka.is_published %}
            <form action="" method="post">
                {% csrf_token %}
                <div class="alert alert-warning">
                    Po opublikowani eureki, będzie ją można dalej edytować.
                </div>
                <button class="btn btn-primary pull-right" type="submit">Opublikuj</button>
            </form>
        {% else %}
            <div class="alert alert-success">
                Twoja eureka jest publiczna. Znajdziesz ją pod tym linkiem:
                <a href="{% url 'eureka:eureka_detail' eureka.slug %}">{% url 'eureka:eureka_detail' eureka.slug %}</a>
            </div>
        {% endif %}
    </div>
{% endblock %}