eDobromir/eDobromir/urls.py
from ckeditor_uploader import views as ckeditor_views
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.sitemaps.views import sitemap

from profile_account import urls as profile_accounts_urls
from comments import urls as comments_urls
from errors import urls as errors_urls
from eureka import urls as eureka_urls
from search import urls as search_urls
from votes import urls as vote_urls
from content import urls as content_urls
from concept import urls as concept_urls
from tags import urls as tags_urls
from linked import urls as linked_urls
from moderation import urls as moderation_urls
from notification import urls as notification_urls
from favorites import urls as favorites_urls
import sitemaps as sitemaps_urls
import rss as rss_urls


urlpatterns = [
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^panel/sterowania/swiatem/', include(admin.site.urls)),  # admin site

    url(r'^', include(search_urls, namespace='search')),
    url(r'^', include(eureka_urls, namespace='eureka')),
    url(r'^', include(errors_urls, namespace='errors')),
    url(r'^', include(vote_urls, namespace='votes')),
    url(r'^', include(comments_urls,  namespace='comments')),
    url(r'^', include(content_urls,  namespace='content')),
    url(r'^', include(concept_urls,  namespace='concept')),
    url(r'^', include(tags_urls,  namespace='tags')),
    url(r'^', include(linked_urls,  namespace='linked')),
    url(r'^', include(moderation_urls,  namespace='moderation')),
    url(r'^', include(notification_urls,  namespace='notification')),
    url(r'^', include(favorites_urls,  namespace='favorites')),
    url(r'^', include(profile_accounts_urls)),
    url(r'^', include(sitemaps_urls)),
    url(r'^', include(rss_urls)),

    url(r'^ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    url(r'^ckeditor/browse/', login_required(ckeditor_views.browse), name='ckeditor_browse'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

eDobromir/moderation/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *


urlpatterns = [
    url(r'^eureka/(?P<slug>[-\w]+)/report/$', ModerationReportEurekaView.as_view(), name='moderation_report_eureka'),
    url(r'^eureka/(?P<slug>[-\w]+)/comments/(?P<comment_slug>[-\w]+)/report/$', ModerationReportEurekaCommentView.as_view(), name='moderation_report_eureka_comment'),
    # url(r'^eureka/(?P<slug>[-\w]+)/links/(?P<slug>[-\w]+)/report/$', ModerationReportView.as_view(), name='eureka_instruction_detail'),
    #
    url(r'^concept/(?P<slug>[-\w]+)/report/$', ModerationReportConceptView.as_view(), name='moderation_report_concept'),
    url(r'^concept/(?P<slug>[-\w]+)/comments/(?P<comment_slug>[-\w]+)/report/$', ModerationReportConceptCommentView.as_view(), name='moderation_report_concept_comment'),
    # url(r'^concept/(?P<slug>[-\w]+)/links/(?P<slug>[-\w]+)/report/$', ModerationReportView.as_view(), name='eureka_instruction_detail'),
    #
    # url(r'^account/user/(?P<slug>[-\w]+)/report/$', ModerationReportView.as_view(), name='eureka_instruction_detail'),
]

eDobromir/tags/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *


urlpatterns = [
    url(r'^tag/list/$', TagListView.as_view(), name='tag_list'),
    url(r'^sympathizer/list/$', SympathizerListView.as_view(), name='sympathizer_list'),
    url(r'^sympathizer/create/$', SympathizerCreateView.as_view(), name='sympathizer_create'),
]

eDobromir/moderation/models.py
from __future__ import unicode_literals

from django.db import models
from django_extensions.db.models import TimeStampedModel
from django.contrib.auth.models import User


class Moderation(TimeStampedModel):
    created_by = models.ForeignKey(User)
    choiceReason = models.CharField(max_length=100)
    reason = models.TextField(verbose_name='Uzasadnienie', max_length=300)


class ModerationModel(models.Model):
    moderations = models.ManyToManyField(Moderation, blank=True)

    class Meta:
        abstract = True

eDobromir/moderation/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm, ChoiceField, RadioSelect
from .models import Moderation

class ReportModerationForm(ModelForm):
    choices = (
        ('Treść pornograficzna', 'Treść pornograficzna'),
        ('Oszustwo, wprowadza w błąd', 'Oszustwo, wprowadza w błąd'),
        ('Propagowanie nienawiści', 'Propagowanie nienawiści'),
        ('Reklama, spam', 'Reklama, spam'),
        ('Atakowanie, oczernianie', 'Atakowanie, oczernianie'),
        ('Narusza regulamin strony', 'Narusza regulamin strony'),
        ('Niepoprawne tagi', 'Niepoprawne tagi'),
        ('Manipulacja głosami', 'Manipulacja głosami'),
        ('Nie nadaje się', 'Nie nadaje się'),
        ('Duplikat', 'Duplikat'),
        ('Informacje nieprawdiwe', 'Informacje nieprawdiwe'),
        ('Treść nieodpowiednia', 'Treść nieodpowiednia'),
        ('Inne', 'Inne'),
    )

    choiceReason = ChoiceField(widget=RadioSelect, choices=choices, label='Powód')

    class Meta:
        model = Moderation
        fields = ['choiceReason', 'reason']

eDobromir/moderation/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import HttpResponse
from django.views.generic import CreateView
from .models import Moderation
from .forms import ReportModerationForm
from eureka.models import Eureka
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from concept.models import Concept
from django.contrib.auth.mixins import LoginRequiredMixin
from administration.views import RatelimitUserOrIpView
from django.forms.utils import ValidationError


class ModerationReportView(LoginRequiredMixin, RatelimitUserOrIpView, CreateView):
    model = Moderation
    form_class = ReportModerationForm
    moderation_object = None

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super(ModerationReportView, self).form_valid(form)

    def moderation_action(self):
        if not self.moderation_object.moderations.filter(created_by__in=[self.request.user.id]).exists():
            self.moderation_object.moderations.add(self.object)
            messages.info(self.request, 'Treść została zgłoszona prawidłowo')
        else:
            self.object.delete()
            messages.info(self.request, 'Już zgłosiłeś tą treść')


class ModerationReportEurekaView(ModerationReportView):
    def dispatch(self, request, *args, **kwargs):
        self.moderation_object = Eureka.objects.get(slug=self.kwargs['slug'])
        return super(ModerationReportEurekaView, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        self.moderation_action()
        return reverse_lazy('eureka:eureka_detail', kwargs={'slug':self.kwargs['slug']})


class ModerationReportConceptView(ModerationReportView):
    def dispatch(self, request, *args, **kwargs):
        self.moderation_object = Concept.objects.get(slug=self.kwargs['slug'])
        return super(ModerationReportConceptView, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        self.moderation_action()
        return reverse_lazy('concept:concept_detail', kwargs={'slug':self.kwargs['slug']})


class ModerationReportEurekaCommentView(ModerationReportView):
    def dispatch(self, request, *args, **kwargs):
        self.moderation_object = Eureka.objects.get(slug=self.kwargs['slug']).comments.get(slug=self.kwargs['comment_slug'])
        return super(ModerationReportEurekaCommentView, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        self.moderation_action()
        return reverse_lazy('eureka:eureka_detail', kwargs={'slug':self.kwargs['slug']})


class ModerationReportConceptCommentView(ModerationReportView):
    def dispatch(self, request, *args, **kwargs):
        self.moderation_object = Concept.objects.get(slug=self.kwargs['slug']).comments.get(slug=self.kwargs['comment_slug'])
        return super(ModerationReportConceptCommentView, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        self.moderation_action()
        return reverse_lazy('concept:concept_detail', kwargs={'slug':self.kwargs['slug']})

eDobromir/moderation/templates/moderation_report_comment_create.html
{% load bootstrap3 %}

<a class="create_report_content_link link-tab {% if was_report %}link-tab-active{% endif %}" data-toggle="modal" data-target="#content_report_create_modal" data-action="{% block form_url %}{% endblock %}">
    {% if not was_report %}
        <i class="fa fa-flag-o" aria-hidden="true"></i>
    {% else %}
        <i class="fa fa-flag" aria-hidden="true"></i>
    {% endif %}
    Zgłoś
</a>

eDobromir/moderation/templates/moderation_report_concept_comment_create.html
{% extends 'moderation_report_comment_create.html' %}

{% block form_url %}{% url 'moderation:moderation_report_concept_comment' concept.slug reportObject.slug %}{% endblock %}

eDobromir/moderation/templates/moderation_report_concept_create.html
{% extends 'moderation_report_create.html' %}

{% block form_url %}{% url 'moderation:moderation_report_concept' reportObject.slug %}{% endblock %}

eDobromir/moderation/templates/moderation_report_create.html
{% load bootstrap3 %}

<a class="create_report_content_link link-tab {% if was_report %}link-tab-active{% endif %}" data-toggle="modal" data-target="#content_report_create_modal" data-action="{% block form_url %}{% endblock %}">
    {% if not was_report %}
        <i class="fa fa-flag-o" aria-hidden="true"></i>
    {% else %}
        <i class="fa fa-flag" aria-hidden="true"></i>
    {% endif %}
    Zgłoś
</a>

eDobromir/moderation/templates/moderation_report_detail.html
{% load bootstrap3 %}
{% load static %}
{% load eureka_templatetags %}
{% load comments_templatetags %}
{% load profile_account_templatetags %}

<p>
    Zgłosili <strong>{{ reportObject.moderations.count|default:'0' }}</strong>
    <small class="pull-right">
        <a type="button"
                class="vote_detail_link link-tab"
                data-toggle="modal"
                data-target="#report_detail_modal">
            <i class="fa fa-eye" aria-hidden="true"></i> Pokaż
        </a>
    </small>
</p>

<div class="modal" id="report_detail_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Użytkownik</th>
                            <th>Dzień</th>
                            <th>Powód</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for moderation in reportObject.moderations.all %}
                            <tr>
                                <td>{% render_profile_username moderation.created_by %}</td>
                                <td>{{ moderation.created }}</td>
                                <td>{{ moderation.choiceReason }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
            </div>
        </div>
    </div>
</div>

eDobromir/moderation/templates/moderation_report_eureka_comment_create.html
{% extends 'moderation_report_comment_create.html' %}

{% block form_url %}{% url 'moderation:moderation_report_eureka_comment' eureka.slug reportObject.slug %}{% endblock %}

eDobromir/moderation/templates/moderation_report_eureka_create.html
{% extends 'moderation_report_create.html' %}

{% block form_url %}{% url 'moderation:moderation_report_eureka' reportObject.slug %}{% endblock %}

eDobromir/moderation/templates/moderation_report_modal.html
{% load bootstrap3 %}

<div class="modal" id="content_report_create_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <div class="alert alert-danger">
                    <strong>Zgłoś treść</strong>
                </div>
            </div>
            <div class="modal-body">
                {% if not request.user.is_authenticated %}
                    <div class="alert alert-warning">
                        Musisz być zalogowanym by móc zgłaszać treści. <a href="{% url 'account_login_signup' %}">Zaloguj się</a>
                    </div>
                {% else %}
                    <form action="" method="POST" id="content_report_create_form">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                    </form>
                {% endif %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
                {% if request.user.is_authenticated %}
                    <button type="submit" class="btn btn-primary" form="content_report_create_form" id="content_report_create_button">Zgłoś</button>
                {% endif %}
            </div>
        </div>
    </div>
</div>